services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: The12ThDoorAdmin
      MONGO_INITDB_ROOT_PASSWORD: P@ssWord12!